services:
  ncast:
    image: nowcast-test:13.2.0
    build:
      context: .
      dockerfile: Dockerfile
    gpus: all
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    tty: true
    stdin_open: true
    working_dir: /workspace
    volumes:
      - .:/workspace
